import { EXTRA_BLOCK_DEFINITIONS } from "./creativeContent.js";

const BASE_BLOCK_TEXTURE_KEYS = [
  "grass_top",
  "grass_side",
  "grass_side_overlay",
  "dirt",
  "stone",
  "sand",
  "sandstone",
  "log_side",
  "log_top",
  "spruce_log_side",
  "spruce_log_top",
  "jungle_log_side",
  "jungle_log_top",
  "birch_log_side",
  "birch_log_top",
  "acacia_log_side",
  "acacia_log_top",
  "dark_oak_log_side",
  "dark_oak_log_top",
  "leaves",
  "spruce_leaves",
  "jungle_leaves",
  "birch_leaves",
  "acacia_leaves",
  "dark_oak_leaves",
  "plank",
  "clay",
  "gravel",
  "cobblestone",
  "coal_ore",
  "iron_ore",
  "copper_ore",
  "gold_ore",
  "diamond_ore",
  "red_sand",
  "terracotta",
  "white_terracotta",
  "snow",
  "snow_grass_side",
  "moss",
  "meadow_grass_top",
  "meadow_grass_side",
  "dry_grass_top",
  "dry_grass_side",
  "coarse_dirt",
  "savanna_grass_top",
  "savanna_grass_side",
  "mycelium_top",
  "mycelium_side",
  "limestone",
  "basalt",
  "slate",
  "granite",
  "diorite",
  "andesite",
  "deepslate",
  "ice",
  "packed_ice",
  "wildflower",
  "fern",
  "tall_grass",
  "dandelion",
  "poppy",
  "blue_orchid",
  "dead_bush",
  "berry_bush",
  "sugar_cane",
  "pumpkin_side",
  "pumpkin_top",
  "melon_side",
  "melon_top",
  "vine",
  "clover",
  "savanna_shrub",
  "brown_mushroom",
  "red_mushroom",
  "waterlily",
  "sunflower",
  "double_grass_bottom",
  "double_grass_top",
  "podzol_top",
  "podzol_side",
  "jungle_grass_top",
  "jungle_grass_side",
  "mud",
  "cactus_side",
  "cactus_top",
  "water",
  "bedrock",
  "crafting_top",
  "crafting_side",
  "crafting_front",
];

const EXTRA_BLOCK_TEXTURE_KEYS = EXTRA_BLOCK_DEFINITIONS
  .flatMap((definition) => [definition.texture, ...Object.values(definition.textures ?? {})])
  .filter(Boolean);

const SHAPE_AUXILIARY_TEXTURE_KEYS = [
  "anvil_base",
  "anvil_top_damaged_0",
  "iron_bars",
  "trapdoor",
  "iron_trapdoor",
  "glass",
  "glass_pane_top",
  "door_wood_lower",
  "door_wood_upper",
  "door_spruce_lower",
  "door_spruce_upper",
  "door_birch_lower",
  "door_birch_upper",
  "door_jungle_lower",
  "door_jungle_upper",
  "door_acacia_lower",
  "door_acacia_upper",
  "door_dark_oak_lower",
  "door_dark_oak_upper",
  "door_iron_lower",
  "door_iron_upper",
];

export const BLOCK_TEXTURE_KEYS = [...new Set([...BASE_BLOCK_TEXTURE_KEYS, ...EXTRA_BLOCK_TEXTURE_KEYS, ...SHAPE_AUXILIARY_TEXTURE_KEYS])];

export const ATLAS_TILE_SIZE = 16;
export const ATLAS_TILE_PADDING = 24;
export const ATLAS_CELL_SIZE = ATLAS_TILE_SIZE + ATLAS_TILE_PADDING * 2;
export const ATLAS_COLUMNS = 8;
export const ATLAS_ROWS = 2 ** Math.ceil(Math.log2(Math.ceil(BLOCK_TEXTURE_KEYS.length / ATLAS_COLUMNS)));

// Texture filenames from src/assets/blocks. Entries without an exact block in
// the zip are intentionally mapped to the closest matching existing texture.
export const BLOCK_TEXTURE_FILES = {
  grass_top: "grass_top.png",
  grass_side: "grass_side.png",
  grass_side_overlay: "grass_side_overlay.png",
  dirt: "dirt.png",
  stone: "stone.png",
  sand: "sand.png",
  sandstone: "sandstone_normal.png",
  log_side: "log_oak.png",
  log_top: "log_oak_top.png",
  spruce_log_side: "log_spruce.png",
  spruce_log_top: "log_spruce_top.png",
  jungle_log_side: "log_jungle.png",
  jungle_log_top: "log_jungle_top.png",
  birch_log_side: "log_birch.png",
  birch_log_top: "log_birch_top.png",
  acacia_log_side: "log_acacia.png",
  acacia_log_top: "log_acacia_top.png",
  dark_oak_log_side: "log_big_oak.png",
  dark_oak_log_top: "log_big_oak_top.png",
  leaves: "leaves_oak.png",
  spruce_leaves: "leaves_spruce.png",
  jungle_leaves: "leaves_jungle.png",
  birch_leaves: "leaves_birch.png",
  acacia_leaves: "leaves_acacia.png",
  dark_oak_leaves: "leaves_big_oak.png",
  plank: "planks_oak.png",
  clay: "clay.png",
  gravel: "gravel.png",
  cobblestone: "cobblestone.png",
  coal_ore: "coal_ore.png",
  iron_ore: "iron_ore.png",
  copper_ore: "iron_ore.png",
  gold_ore: "gold_ore.png",
  diamond_ore: "diamond_ore.png",
  red_sand: "red_sand.png",
  terracotta: "hardened_clay.png",
  white_terracotta: "hardened_clay_stained_white.png",
  snow: "snow.png",
  snow_grass_side: "grass_side_snowed.png",
  moss: "cobblestone_mossy.png",
  meadow_grass_top: "grass_top.png",
  meadow_grass_side: "grass_side.png",
  dry_grass_top: "grass_top.png",
  dry_grass_side: "grass_side.png",
  coarse_dirt: "coarse_dirt.png",
  savanna_grass_top: "grass_top.png",
  savanna_grass_side: "grass_side.png",
  mycelium_top: "mycelium_top.png",
  mycelium_side: "mycelium_side.png",
  limestone: "stone_diorite.png",
  basalt: "obsidian.png",
  slate: "stone.png",
  granite: "stone_granite.png",
  diorite: "stone_diorite.png",
  andesite: "stone_andesite.png",
  deepslate: "stone.png",
  ice: "ice.png",
  packed_ice: "ice_packed.png",
  wildflower: "flower_houstonia.png",
  fern: "fern.png",
  tall_grass: "tallgrass.png",
  dandelion: "flower_dandelion.png",
  poppy: "flower_rose.png",
  blue_orchid: "flower_blue_orchid.png",
  dead_bush: "deadbush.png",
  berry_bush: "cocoa_stage_2.png",
  sugar_cane: "reeds.png",
  pumpkin_side: "pumpkin_side.png",
  pumpkin_top: "pumpkin_top.png",
  melon_side: "melon_side.png",
  melon_top: "melon_top.png",
  vine: "vine.png",
  clover: "tallgrass.png",
  savanna_shrub: "deadbush.png",
  brown_mushroom: "mushroom_brown.png",
  red_mushroom: "mushroom_red.png",
  waterlily: "waterlily.png",
  sunflower: "double_plant_sunflower_front.png",
  double_grass_bottom: "double_plant_grass_bottom.png",
  double_grass_top: "double_plant_grass_top.png",
  podzol_top: "dirt_podzol_top.png",
  podzol_side: "dirt_podzol_side.png",
  jungle_grass_top: "grass_top.png",
  jungle_grass_side: "grass_side.png",
  mud: "dirt.png",
  cactus_side: "cactus_side.png",
  cactus_top: "cactus_top.png",
  water: "water_still.png",
  bedrock: "bedrock.png",
  crafting_top: "crafting_table_top.png",
  crafting_side: "crafting_table_side.png",
  crafting_front: "crafting_table_front.png",
};

for (const key of EXTRA_BLOCK_TEXTURE_KEYS) {
  BLOCK_TEXTURE_FILES[key] ??= `${key}.png`;
}

for (const key of SHAPE_AUXILIARY_TEXTURE_KEYS) {
  BLOCK_TEXTURE_FILES[key] ??= `${key}.png`;
}
