export const Biome = {
  OCEAN: "ocean",
  DEEP_OCEAN: "deep_ocean",
  FROZEN_OCEAN: "frozen_ocean",
  PLAINS: "plains",
  SUNFLOWER_PLAINS: "sunflower_plains",
  DESERT: "desert",
  DESERT_HILLS: "desert_hills",
  DESERT_M: "desert_m",
  MEADOW: "meadow",
  GROVE: "grove",
  SNOWY_SLOPES: "snowy_slopes",
  JAGGED_PEAKS: "jagged_peaks",
  FROZEN_PEAKS: "frozen_peaks",
  STONY_PEAKS: "stony_peaks",
  EXTREME_HILLS: "extreme_hills",
  EXTREME_HILLS_EDGE: "extreme_hills_edge",
  EXTREME_HILLS_PLUS: "extreme_hills_plus",
  EXTREME_HILLS_M: "extreme_hills_m",
  EXTREME_HILLS_PLUS_M: "extreme_hills_plus_m",
  FOREST: "forest",
  FOREST_HILLS: "forest_hills",
  FLOWER_FOREST: "flower_forest",
  BIRCH_FOREST: "birch_forest",
  BIRCH_FOREST_HILLS: "birch_forest_hills",
  BIRCH_FOREST_M: "birch_forest_m",
  BIRCH_FOREST_HILLS_M: "birch_forest_hills_m",
  ROOFED_FOREST: "roofed_forest",
  ROOFED_FOREST_M: "roofed_forest_m",
  TAIGA: "taiga",
  TAIGA_HILLS: "taiga_hills",
  TAIGA_M: "taiga_m",
  COLD_TAIGA: "cold_taiga",
  COLD_TAIGA_HILLS: "cold_taiga_hills",
  COLD_TAIGA_M: "cold_taiga_m",
  MEGA_TAIGA: "mega_taiga",
  MEGA_TAIGA_HILLS: "mega_taiga_hills",
  MEGA_SPRUCE_TAIGA: "mega_spruce_taiga",
  MEGA_SPRUCE_TAIGA_HILLS: "mega_spruce_taiga_hills",
  SWAMPLAND: "swampland",
  SWAMPLAND_M: "swampland_m",
  RIVER: "river",
  FROZEN_RIVER: "frozen_river",
  ICE_PLAINS: "ice_plains",
  ICE_MOUNTAINS: "ice_mountains",
  ICE_SPIKES: "ice_spikes",
  MUSHROOM_ISLAND: "mushroom_island",
  MUSHROOM_SHORE: "mushroom_shore",
  BEACH: "beach",
  STONE_BEACH: "stone_beach",
  COLD_BEACH: "cold_beach",
  JUNGLE: "jungle",
  JUNGLE_HILLS: "jungle_hills",
  JUNGLE_EDGE: "jungle_edge",
  JUNGLE_M: "jungle_m",
  JUNGLE_EDGE_M: "jungle_edge_m",
  SAVANNA: "savanna",
  SAVANNA_PLATEAU: "savanna_plateau",
  SAVANNA_M: "savanna_m",
  SAVANNA_PLATEAU_M: "savanna_plateau_m",
  MESA: "mesa",
  MESA_PLATEAU_F: "mesa_plateau_f",
  MESA_PLATEAU: "mesa_plateau",
  MESA_BRYCE: "mesa_bryce",
  MESA_PLATEAU_F_M: "mesa_plateau_f_m",
  MESA_PLATEAU_M: "mesa_plateau_m",
};

export function createBiomeDefinitions(Block) {
  return {
    [Biome.OCEAN]: biome("Ocean", Block.SAND, Block.GRAVEL),
    [Biome.DEEP_OCEAN]: biome("Deep Ocean", Block.GRAVEL, Block.GRAVEL),
    [Biome.FROZEN_OCEAN]: biome("Frozen Ocean", Block.GRAVEL, Block.GRAVEL),
    [Biome.PLAINS]: biome("Plains", Block.GRASS, Block.DIRT, "oak", 0.76, 0.009),
    [Biome.SUNFLOWER_PLAINS]: biome("Sunflower Plains", Block.GRASS, Block.DIRT, "oak", 0.78, 0.008),
    [Biome.DESERT]: biome("Desert", Block.SAND, Block.SANDSTONE, "oak", 0.94, 0.003),
    [Biome.DESERT_HILLS]: biome("Desert Hills", Block.SAND, Block.SANDSTONE, "oak", 0.93, 0.003),
    [Biome.DESERT_M]: biome("Desert M", Block.SAND, Block.SANDSTONE, "oak", 0.94, 0.003),
    [Biome.MEADOW]: biome("Meadow", Block.GRASS, Block.DIRT, "oak", 0.92, 0.0018),
    [Biome.GROVE]: biome("Grove", Block.SNOW, Block.DIRT, "spruce", 0.24, 0.075),
    [Biome.SNOWY_SLOPES]: biome("Snowy Slopes", Block.SNOW, Block.SNOW),
    [Biome.JAGGED_PEAKS]: biome("Jagged Peaks", Block.STONE, Block.STONE),
    [Biome.FROZEN_PEAKS]: biome("Frozen Peaks", Block.SNOW, Block.PACKED_ICE),
    [Biome.STONY_PEAKS]: biome("Stony Peaks", Block.STONE, Block.STONE),
    [Biome.EXTREME_HILLS]: biome("Extreme Hills", Block.GRASS, Block.DIRT, null, 1, 0),
    [Biome.EXTREME_HILLS_EDGE]: biome("Extreme Hills Edge", Block.GRASS, Block.DIRT, null, 1, 0),
    [Biome.EXTREME_HILLS_PLUS]: biome("Extreme Hills+", Block.GRASS, Block.DIRT, "spruce", 0.68, 0.012),
    [Biome.EXTREME_HILLS_M]: biome("Extreme Hills M", Block.STONE, Block.STONE, null, 1, 0),
    [Biome.EXTREME_HILLS_PLUS_M]: biome("Extreme Hills+ M", Block.STONE, Block.STONE, "spruce", 0.68, 0.012),
    // FIX: Forest tree density reduced. forestThreshold raised so fewer blocks qualify,
    // treeChance lowered so qualifying blocks are less likely to have a tree.
    // Old: (0.4, 0.028) → New: (0.52, 0.020). Still clearly a forest, just breathable.
    [Biome.FOREST]: biome("Forest", Block.GRASS, Block.DIRT, "oak", 0.52, 0.020),
    [Biome.FOREST_HILLS]: biome("Forest Hills", Block.GRASS, Block.DIRT, "oak", 0.50, 0.022),
    [Biome.FLOWER_FOREST]: biome("Flower Forest", Block.GRASS, Block.DIRT, "oak", 0.72, 0.008),
    [Biome.BIRCH_FOREST]: biome("Birch Forest", Block.GRASS, Block.DIRT, "birch", 0.50, 0.026),
    [Biome.BIRCH_FOREST_HILLS]: biome("Birch Forest Hills", Block.GRASS, Block.DIRT, "birch", 0.48, 0.024),
    [Biome.BIRCH_FOREST_M]: biome("Birch Forest M", Block.GRASS, Block.DIRT, "tall_birch", 0.46, 0.028),
    [Biome.BIRCH_FOREST_HILLS_M]: biome("Birch Forest Hills M", Block.GRASS, Block.DIRT, "tall_birch", 0.44, 0.026),
    // FIX: Roofed Forest was extremely dense. Old: (0.22, 0.055) — 78% area coverage * 5.5% chance.
    // New: (0.44, 0.036) — 56% area coverage * 3.6% chance. Still dense and dark, not suffocating.
    [Biome.ROOFED_FOREST]: biome("Roofed Forest", Block.GRASS, Block.DIRT, "dark_oak", 0.44, 0.036),
    [Biome.ROOFED_FOREST_M]: biome("Roofed Forest M", Block.GRASS, Block.DIRT, "dark_oak", 0.40, 0.040),
    [Biome.TAIGA]: biome("Taiga", Block.PODZOL, Block.DIRT, "spruce", 0.36, 0.032),
    [Biome.TAIGA_HILLS]: biome("Taiga Hills", Block.PODZOL, Block.DIRT, "spruce", 0.33, 0.034),
    [Biome.TAIGA_M]: biome("Taiga M", Block.PODZOL, Block.DIRT, "spruce", 0.30, 0.032),
    [Biome.COLD_TAIGA]: biome("Cold Taiga", Block.SNOW_GRASS, Block.DIRT, "spruce", 0.42, 0.026),
    [Biome.COLD_TAIGA_HILLS]: biome("Cold Taiga Hills", Block.SNOW_GRASS, Block.DIRT, "spruce", 0.38, 0.028),
    [Biome.COLD_TAIGA_M]: biome("Cold Taiga M", Block.SNOW_GRASS, Block.DIRT, "spruce", 0.34, 0.026),
    [Biome.MEGA_TAIGA]: biome("Mega Taiga", Block.PODZOL, Block.DIRT, "mega_spruce", 0.28, 0.045),
    [Biome.MEGA_TAIGA_HILLS]: biome("Mega Taiga Hills", Block.PODZOL, Block.DIRT, "mega_spruce", 0.24, 0.045),
    [Biome.MEGA_SPRUCE_TAIGA]: biome("Mega Spruce Taiga", Block.PODZOL, Block.DIRT, "mega_spruce", 0.24, 0.052),
    [Biome.MEGA_SPRUCE_TAIGA_HILLS]: biome("Mega Spruce Taiga Hills", Block.PODZOL, Block.DIRT, "mega_spruce", 0.22, 0.05),
    [Biome.SWAMPLAND]: biome("Swampland", Block.GRASS, Block.DIRT, "swamp_oak", 0.44, 0.030),
    [Biome.SWAMPLAND_M]: biome("Swampland M", Block.GRASS, Block.DIRT, "swamp_oak", 0.40, 0.030),
    [Biome.RIVER]: biome("River", Block.GRAVEL, Block.GRAVEL),
    [Biome.FROZEN_RIVER]: biome("Frozen River", Block.ICE, Block.GRAVEL),
    [Biome.ICE_PLAINS]: biome("Ice Plains", Block.SNOW_GRASS, Block.DIRT, "spruce", 0.7, 0.006),
    [Biome.ICE_MOUNTAINS]: biome("Ice Mountains", Block.SNOW, Block.DIRT, "spruce", 0.72, 0.006),
    [Biome.ICE_SPIKES]: biome("Ice Spikes", Block.SNOW, Block.PACKED_ICE),
    [Biome.MUSHROOM_ISLAND]: biome("Mushroom Island", Block.MYCELIUM, Block.DIRT),
    [Biome.MUSHROOM_SHORE]: biome("Mushroom Shore", Block.MYCELIUM, Block.DIRT),
    [Biome.BEACH]: biome("Beach", Block.SAND, Block.SAND),
    [Biome.STONE_BEACH]: biome("Stone Beach", Block.STONE, Block.GRAVEL),
    [Biome.COLD_BEACH]: biome("Cold Beach", Block.SAND, Block.GRAVEL),
    [Biome.JUNGLE]: biome("Jungle", Block.GRASS, Block.DIRT, "jungle", 0.33, 0.045),
    [Biome.JUNGLE_HILLS]: biome("Jungle Hills", Block.GRASS, Block.DIRT, "jungle", 0.30, 0.048),
    [Biome.JUNGLE_EDGE]: biome("Jungle Edge", Block.GRASS, Block.DIRT, "jungle", 0.58, 0.018),
    [Biome.JUNGLE_M]: biome("Jungle M", Block.GRASS, Block.DIRT, "jungle", 0.28, 0.05),
    [Biome.JUNGLE_EDGE_M]: biome("Jungle Edge M", Block.GRASS, Block.DIRT, "jungle", 0.52, 0.018),
    // FIX: Savanna acacia density reduced. User reported trees were too dense.
    // Old: (0.52, 0.034) → New: (0.66, 0.020). Still scattered acacias, not a forest.
    [Biome.SAVANNA]: biome("Savanna", Block.GRASS, Block.DIRT, "acacia", 0.66, 0.020),
    [Biome.SAVANNA_PLATEAU]: biome("Savanna Plateau", Block.GRASS, Block.DIRT, "acacia", 0.68, 0.018),
    [Biome.SAVANNA_M]: biome("Savanna M", Block.COARSE_DIRT, Block.DIRT, "acacia", 0.72, 0.012),
    [Biome.SAVANNA_PLATEAU_M]: biome("Savanna Plateau M", Block.COARSE_DIRT, Block.STONE, "acacia", 0.76, 0.010),
    [Biome.MESA]: biome("Mesa", Block.RED_SAND, Block.TERRACOTTA, "acacia", 0.92, 0.004),
    [Biome.MESA_PLATEAU_F]: biome("Mesa Plateau F", Block.RED_SAND, Block.TERRACOTTA, "oak", 0.72, 0.008),
    [Biome.MESA_PLATEAU]: biome("Mesa Plateau", Block.TERRACOTTA, Block.TERRACOTTA, "acacia", 0.93, 0.003),
    [Biome.MESA_BRYCE]: biome("Mesa Bryce", Block.TERRACOTTA, Block.TERRACOTTA, "acacia", 0.94, 0.003),
    [Biome.MESA_PLATEAU_F_M]: biome("Mesa Plateau F M", Block.TERRACOTTA, Block.TERRACOTTA, "oak", 0.78, 0.006),
    [Biome.MESA_PLATEAU_M]: biome("Mesa Plateau M", Block.TERRACOTTA, Block.TERRACOTTA, "acacia", 0.93, 0.003),
  };
}

function biome(name, surface, filler, tree = null, forestThreshold = 1, treeChance = 0) {
  return {
    name,
    surface,
    filler,
    tree,
    forestThreshold,
    treeChance,
  };
}
